// =================================================================================================
//! @file steer_json_constants.h
//! @author Gary Woodcock (gary@anametric.com)
//! @brief This file defines the common JSON tags and values used by the STandard Entropy
//! Evaluation Report (STEER) framework. 
//! @remarks Requires ANSI C99 (or better) compliant compilers.
//! @remarks Supported host operating systems: Any *nix
//! @date 2021-09-24
//! @copyright Copyright (c) 2024 Anametric, Inc. All rights reserved.
//! 
//  Includes
// =================================================================================================
#ifdef __cplusplus
    #pragma once
#endif

#ifndef __STEER_JSON_CONSTANTS_H__
#define __STEER_JSON_CONSTANTS_H__

// =================================================================================================
//  Macros
// =================================================================================================

// JSON tags
#define STEER_JSON_TAG_ACCURACY                                             "accuracy (ACC)"
#define STEER_JSON_TAG_ACTUAL_OBSERVED_PEAKS_LESS_THAN_95_PERCENT           "actual observed number of peaks less than 95% peak height threshold"
#define STEER_JSON_TAG_ACTUAL_FAIL_COUNT                                    "actual fail count (F)"
#define STEER_JSON_TAG_ACTUAL_PASS_COUNT                                    "actual pass count (P)"
#define STEER_JSON_TAG_APPROXIMATE_ENTROPY                                  "approximate entropy"
#define STEER_JSON_TAG_ARCHITECTURE                                         "architecture"
#define STEER_JSON_TAG_ATTRIBUTES                                           "attributes"
#define STEER_JSON_TAG_AUTHORS                                              "authors"
#define STEER_JSON_TAG_BALANCED_ACCURACY                                    "balanced accuracy (BA)"
#define STEER_JSON_TAG_BITSTREAM_COUNT                                      "bitstream count"
#define STEER_JSON_TAG_BITSTREAM_ID                                         "bitstream id"
#define STEER_JSON_TAG_BITSTREAM_LENGTH                                     "bitstream length"
#define STEER_JSON_TAG_BITSTREAM_TESTS_PASSED                               "bitstream tests passed"
#define STEER_JSON_TAG_BITSTREAMS_TESTED                                    "bitstreams tested"
#define STEER_JSON_TAG_BITS_DISCARDED                                       "bits discarded"
#define STEER_JSON_TAG_BLOCK                                                "block"
#define STEER_JSON_TAG_BLOCK_LENGTH                                         "block length"
#define STEER_JSON_TAG_SUBSEQUENCE_LENGTH                                   "subsequence length"
#define STEER_JSON_TAG_MAXLAG                                               "maxlag"
#define STEER_JSON_TAG_ADD_BIAS                                             "add bias"
#define STEER_JSON_TAG_DO_THRESHOLD                                         "do threshold"
#define STEER_JSON_TAG_BITSTREAM_SUBSET_INDEX                               "bitstream subset index"
#define STEER_JSON_TAG_CALCULATIONS                                         "calculations"
#define STEER_JSON_TAG_CHI_SQUARED                                          "chi squared"
#define STEER_JSON_TAG_COMPLEMENTARY_ERROR_FUNCTION_ARGUMENT                "complementary error function (erfc) argument"
#define STEER_JSON_TAG_COMPLETION_TIME                                      "completion time"
#define STEER_JSON_TAG_COMPLEXITY                                           "complexity"
#define STEER_JSON_TAG_CONFIDENCE_INTERVAL                                  "confidence interval"
#define STEER_JSON_TAG_CONFIGURATION                                        "configuration"
#define STEER_JSON_TAG_CONFIGURATION_ID                                     "configuration id"
#define STEER_JSON_TAG_CONFIGURATION_NAME                                   "configuration name"
#define STEER_JSON_TAG_CONFIGURATIONS                                       "configurations"
#define STEER_JSON_TAG_CONFUSION_MATRIX                                     "confusion matrix"
#define STEER_JSON_TAG_CONFUSION_MATRIX_STATISTICS                          "confusion matrix statistics"
#define STEER_JSON_TAG_CONTACT                                              "contact"
#define STEER_JSON_TAG_CONTRIBUTORS                                         "contributors"
#define STEER_JSON_TAG_CRITERIA                                             "criteria"
#define STEER_JSON_TAG_CRITERION                                            "criterion"
#define STEER_JSON_TAG_DATA_TYPE                                            "data type"
#define STEER_JSON_TAG_DEFAULT_VALUE                                        "default value"
#define STEER_JSON_TAG_DEGREES_OF_FREEDOM                                   "degrees of freedom"
#define STEER_JSON_TAG_DESCRIPTION                                          "description"
#define STEER_JSON_TAG_DIAGNOSTIC_ODDS_RATIO                                "diagnostic odds ratio (DOR)"
#define STEER_JSON_TAG_DIRECTION                                            "direction"
#define STEER_JSON_TAG_ENTROPY_DISTRIBUTION                                 "entropy distribution"
#define STEER_JSON_TAG_ENTROPY_SOURCE                                       "entropy source"
#define STEER_JSON_TAG_ERROR_RATE                                           "error rate"
#define STEER_JSON_TAG_ETA                                                  "eta"
#define STEER_JSON_TAG_EVALUATION                                           "evaluation"
#define STEER_JSON_TAG_EXPECTED                                             "expected"
#define STEER_JSON_TAG_EXPECTED_PEAKS_LESS_THAN_95_PERCENT                  "expected number of peaks less than 95% peak height threshold"
#define STEER_JSON_TAG_EXPECTED_RESULTS                                     "expected results"
#define STEER_JSON_TAG_EXPECTED_VALUE                                       "expected value"
#define STEER_JSON_TAG_F1_SCORE                                             "F1 score"
#define STEER_JSON_TAG_FALSE_DISCOVERY_RATE                                 "false discovery rate (FDR)"
#define STEER_JSON_TAG_FALSE_NEGATIVE_RATE                                  "false negative rate (FNR)"
#define STEER_JSON_TAG_FALSE_NEGATIVES                                      "false negatives (FN)"
#define STEER_JSON_TAG_FALSE_OMISSION_RATE                                  "false omission rate (FOR)"
#define STEER_JSON_TAG_FALSE_POSITIVE_RATE                                  "false positive rate (FPR)"
#define STEER_JSON_TAG_FALSE_POSITIVES                                      "false positives (FP)"
#define STEER_JSON_TAG_FOWLKES_MALLOWS_INDEX                                "Fowlkes-Mallows index (FM)"
#define STEER_JSON_TAG_FREQUENCIES                                          "frequencies"
#define STEER_JSON_TAG_GENERALIZED_SERIAL_STATISTICS                        "generalized serial statistics"
#define STEER_JSON_TAG_ID                                                   "id"
#define STEER_JSON_TAG_INFORMEDNESS                                         "informedness (BM)"
#define STEER_JSON_TAG_INPUT                                                "input"
#define STEER_JSON_TAG_INPUT_FORMAT                                         "input format"
#define STEER_JSON_TAG_INPUTS_DIRECTORY                                     "inputs directory"
#define STEER_JSON_TAG_LABEL                                                "label"
#define STEER_JSON_TAG_LINEAR_COMPLEXITY_STATISTIC_FREQUENCIES              "linear complexity statistic frequencies"
#define STEER_JSON_TAG_LOG_E_2                                              "natural logarithm of 2.0"
#define STEER_JSON_TAG_LOWER_BOUND                                          "lower bound"
#define STEER_JSON_TAG_M                                                    "m"
#define STEER_JSON_TAG_M_MINUS_ONE                                          "m - 1"
#define STEER_JSON_TAG_M_MINUS_TWO                                          "m - 2"
#define STEER_JSON_TAG_M_PLUS_ONE                                           "m + 1"
#define STEER_JSON_TAG_MAINTAINERS                                          "maintainers"
#define STEER_JSON_TAG_MARKEDNESS                                           "markedness (MK)"
#define STEER_JSON_TAG_MATTHEWS_CORRELATION_COEFFICIENT                     "Matthew's correlation coefficient (MCC)"
#define STEER_JSON_TAG_MAXIMUM_PARTIAL_SUM                                  "maximum partial sum"
#define STEER_JSON_TAG_MAXIMUM_VALUE                                        "maximum value"
#define STEER_JSON_TAG_MEASURED                                             "measured"
#define STEER_JSON_TAG_METRICS                                              "metrics"
#define STEER_JSON_TAG_MINIMUM_BITSTREAM_TESTS_REQUIRED_FOR_SIGNIFICANCE    "minimum bitstream tests required for significance"
#define STEER_JSON_TAG_MINIMUM_BITSTREAM_TESTS_REQUIRED_TO_PASS             "minimum bitstream tests required to pass"
#define STEER_JSON_TAG_MINIMUM_VALUE                                        "minimum value"
#define STEER_JSON_TAG_NAME                                                 "name"
#define STEER_JSON_TAG_NEGATIVE_LIKELIHOOD_RATIO                            "negative likelihood ratio (LR-)"
#define STEER_JSON_TAG_NEGATIVE_PREDICTIVE_VALUE                            "negative predictive value (NPV)"
#define STEER_JSON_TAG_NORMALIZED_DIFF_BETWEEN_PEAKS                        "normalized difference between observed and expected number of frequency components beyond 95% threshold"
#define STEER_JSON_TAG_NTH_PARTIAL_SUM                                      "nth partial sum"
#define STEER_JSON_TAG_NTH_PARTIAL_SUM_OVER_BITSTREAM_LENGTH                "nth partial sum / bitstream length"
#define STEER_JSON_TAG_NULL_HYPOTHESIS                                      "null hypothesis"
#define STEER_JSON_TAG_NUMBER_OF_BLOCKS_IN_INITIALIZATION_SEQUENCE          "number of blocks in initialization sequence"
#define STEER_JSON_TAG_NUMBER_OF_CYCLES                                     "number of cycles"
#define STEER_JSON_TAG_NUMBER_OF_INDEPENDENT_BLOCKS                         "number of independent blocks"
#define STEER_JSON_TAG_NUMBER_OF_MATRICES                                   "number of matrices"
#define STEER_JSON_TAG_NUMBER_OF_NON_OVERLAPPING_BLOCKS_IN_TEST_SEGMENT     "number of non-overlapping blocks in test segment"
#define STEER_JSON_TAG_NUMBER_OF_SUBSTRINGS                                 "number of substrings"
#define STEER_JSON_TAG_ONES                                                 "ones"
#define STEER_JSON_TAG_OPERATING_SYSTEM                                     "operating system"
#define STEER_JSON_TAG_PARALLELIZE_BIT_STREAMS                              "parallelize bitstreams"
#define STEER_JSON_TAG_PARAMETER_NAME                                       "parameter name"
#define STEER_JSON_TAG_PARAMETER_SET                                        "parameter set"
#define STEER_JSON_TAG_PARAMETER_SET_NAME                                   "parameter set name"
#define STEER_JSON_TAG_PARAMETERS                                           "parameters"
#define STEER_JSON_TAG_PARAMETERS_DIRECTORY                                 "parameters directory"
#define STEER_JSON_TAG_PARAMETERS_INFO                                      "parameters info"
#define STEER_JSON_TAG_PERCENTILE                                           "percentile"
#define STEER_JSON_TAG_POSITIVE_LIKELIHOOD_RATIO                            "positive likelihood ratio (LR+)"
#define STEER_JSON_TAG_POSITIVE_PREDICTIVE_VALUE                            "positive predictive value (PPV)"
#define STEER_JSON_TAG_PRE_COMPUTED_EXPECTED_VALUE                          "pre-computed expected value"
#define STEER_JSON_TAG_PRE_COMPUTED_VARIANCE                                "pre-computed variance"
#define STEER_JSON_TAG_PRE_TEST_PROPORTION_OF_ONES                          "pre-test proportion of ones"
#define STEER_JSON_TAG_PRECISION                                            "precision"
#define STEER_JSON_TAG_PREDICTED_FAIL_COUNT                                 "predicted fail count (PN)"
#define STEER_JSON_TAG_PREDICTED_PASS_COUNT                                 "predicted pass count (PP)"
#define STEER_JSON_TAG_PREVALENCE                                           "prevalence"
#define STEER_JSON_TAG_PREVALENCE_THRESHOLD                                 "prevalence threshold (PT)"
#define STEER_JSON_TAG_PROBABILITIES                                        "probabilities"
#define STEER_JSON_TAG_PROBABILITY                                          "probability"
#define STEER_JSON_TAG_PROBABILITY_VALUE                                    "probability value"
#define STEER_JSON_TAG_PROBABILITY_VALUE_FREQUENCIES                        "probability value frequencies"
#define STEER_JSON_TAG_PROBABILITY_VALUE_FROM_CHI_SQUARE_TEST               "probability value from chi-square test"
#define STEER_JSON_TAG_PROBABILITY_VALUE_UNIFORMITY                         "probability value uniformity"
#define STEER_JSON_TAG_PROBABILITY_VALUES                                   "probability values"
#define STEER_JSON_TAG_PROFILE_ID                                           "profile id"
#define STEER_JSON_TAG_PROFILES                                             "profiles"
#define STEER_JSON_TAG_PROGRAM_NAME                                         "program name"
#define STEER_JSON_TAG_PROGRAM_VERSION                                      "program version"
#define STEER_JSON_TAG_RANDOM_EXCURSION_STATE                               "random excursion state"
#define STEER_JSON_TAG_RANDOM_NUMBER_SOURCE                                 "random number source"
#define STEER_JSON_TAG_RANK_30                                              "rank 30"
#define STEER_JSON_TAG_RANK_31                                              "rank 31"
#define STEER_JSON_TAG_RANK_32                                              "rank 32"
#define STEER_JSON_TAG_RANK_FREQUENCIES                                     "rank frequencies"
#define STEER_JSON_TAG_RANK_PROBABILITIES                                   "rank probabilities"
#define STEER_JSON_TAG_RECOMMENDED_BLOCK_LENGTH                             "recommended block length"
#define STEER_JSON_TAG_REFERENCES                                           "references"
#define STEER_JSON_TAG_REJECTION_CONSTRAINT                                 "rejection constraint"
#define STEER_JSON_TAG_REPORT                                               "report"
#define STEER_JSON_TAG_REPORT_LEVEL                                         "report level"
#define STEER_JSON_TAG_REPORT_PROGRESS                                      "report progress"
#define STEER_JSON_TAG_REPORTS_DIRECTORY                                    "reports directory"
#define STEER_JSON_TAG_REPOSITORY                                           "repository"
#define STEER_JSON_TAG_RESULT                                               "result"
#define STEER_JSON_TAG_RESULTS                                              "results"
#define STEER_JSON_TAG_SCHEDULE                                             "schedule"
#define STEER_JSON_TAG_SCHEDULE_ID                                          "schedule id"
#define STEER_JSON_TAG_SERIAL_STATISTICS                                    "serial statistics"
#define STEER_JSON_TAG_SIGNIFICANCE_LEVEL                                   "significance level (alpha)"
#define STEER_JSON_TAG_STANDARD_DEVIATION                                   "standard deviation"
#define STEER_JSON_TAG_STANDARD_NORMAL_FUNCTION                             "standard normal (cumulative distribution) function"
#define STEER_JSON_TAG_STATUS                                               "status"
#define STEER_JSON_TAG_START_TIME                                           "start time"
#define STEER_JSON_TAG_SUBSTRING_LENGTH                                     "substring length"
#define STEER_JSON_TAG_SUITE                                                "suite"
#define STEER_JSON_TAG_SUM                                                  "sum"
#define STEER_JSON_TAG_TEMPLATE                                             "template"
#define STEER_JSON_TAG_TEMPLATE_FREQUENCIES                                 "template frequencies"
#define STEER_JSON_TAG_TEST_ARCHITECTURE                                    "test architecture"
#define STEER_JSON_TAG_TEST_CONDUCTOR                                       "test conductor"
#define STEER_JSON_TAG_TEST_DESCRIPTION                                     "test description"
#define STEER_JSON_TAG_TEST_DURATION                                        "test duration"
#define STEER_JSON_TAG_TEST_ID                                              "test id"
#define STEER_JSON_TAG_TEST_INFO                                            "test info"
#define STEER_JSON_TAG_TEST_INPUT                                           "test input"
#define STEER_JSON_TAG_TEST_INPUTS                                          "test inputs"
#define STEER_JSON_TAG_TEST_INPUTS_DIRECTORY                                "test inputs directory"
#define STEER_JSON_TAG_TEST_NAME                                            "test name"
#define STEER_JSON_TAG_TEST_NOTES                                           "test notes"
#define STEER_JSON_TAG_TEST_PARAMETERS                                      "test parameters"
#define STEER_JSON_TAG_TEST_PARAMETERS_DIRECTORY                            "test parameters directory"
#define STEER_JSON_TAG_TEST_PROGRAM_VERSION                                 "test program version"
#define STEER_JSON_TAG_TEST_REFERENCES                                      "test references"
#define STEER_JSON_TAG_TEST_REPORT                                          "test report"
#define STEER_JSON_TAG_TEST_REPORT_DIRECTORY                                "test report directory"
#define STEER_JSON_TAG_TEST_REPORTS_DIRECTORY                               "test reports directory"
#define STEER_JSON_TAG_TEST_REPORTS                                         "test reports"
#define STEER_JSON_TAG_TEST_SCHEDULE                                        "test schedule"
#define STEER_JSON_TAG_TEST_SPECIFIC                                        "test specific"
#define STEER_JSON_TAG_TEST_STATISTIC                                       "test statistic"
#define STEER_JSON_TAG_TEST_SUITE                                           "test suite"
#define STEER_JSON_TAG_TESTS                                                "tests"
#define STEER_JSON_TAG_THEORETICAL_MEAN                                     "theoretical mean"
#define STEER_JSON_TAG_THEORETICAL_PROBABILITIES                            "theoretical probabilities"
#define STEER_JSON_TAG_THEORETICAL_STANDARD_DEVIATION                       "theoretical standard deviation"
#define STEER_JSON_TAG_THREAD_COUNT                                         "thread count"
#define STEER_JSON_TAG_THREAT_SCORE                                         "threat score (TS)"
#define STEER_JSON_TAG_TIMESTAMP                                            "timestamp"
#define STEER_JSON_TAG_TOTAL_NUMBER_OF_RUNS                                 "total number of runs"
#define STEER_JSON_TAG_TOTAL_ONES                                           "total ones"
#define STEER_JSON_TAG_TOTAL_TESTS                                          "total tests"
#define STEER_JSON_TAG_TOTAL_TESTS_PASSED                                   "total tests passed"
#define STEER_JSON_TAG_TOTAL_VISITS                                         "total visits"
#define STEER_JSON_TAG_TOTAL_ZEROS                                          "total zeros"
#define STEER_JSON_TAG_TRUE_NEGATIVE_RATE                                   "true negative rate (TNR)"
#define STEER_JSON_TAG_TRUE_NEGATIVES                                       "true negatives (TN)"
#define STEER_JSON_TAG_TRUE_POSITIVE_RATE                                   "true positive rate (TPR)"
#define STEER_JSON_TAG_TRUE_POSITIVES                                       "true positives (TP)"
#define STEER_JSON_TAG_UNITS                                                "units"
#define STEER_JSON_TAG_UPPER_BOUND                                          "upper bound"
#define STEER_JSON_TAG_VALIDATIONS                                          "validations"
#define STEER_JSON_TAG_VALUE                                                "value"
#define STEER_JSON_TAG_VALUES                                               "values"
#define STEER_JSON_TAG_VARIANCE                                             "variance"
#define STEER_JSON_TAG_ZEROS                                                "zeros"

// JSON values
#define STEER_JSON_VALUE_ASCII_BITSTREAM                                    "ascii bitstream"
#define STEER_JSON_VALUE_AVERAGE                                            "average"
#define STEER_JSON_VALUE_BITSTREAM                                          "bitstream"
#define STEER_JSON_VALUE_BITSTREAMS                                         "bitstreams"
#define STEER_JSON_VALUE_BITS                                               "bits"
#define STEER_JSON_VALUE_BLOCKS                                             "blocks"
#define STEER_JSON_VALUE_BOOLEAN                                            "boolean"
#define STEER_JSON_VALUE_BYTES                                              "bytes"
#define STEER_JSON_VALUE_COMPREHENSIVE                                      "comprehensive"
#define STEER_JSON_VALUE_CYCLES                                             "cycles"
#define STEER_JSON_VALUE_DEFAULT_FLOATING_POINT_PRECISION                   "6"
#define STEER_JSON_VALUE_DEFAULT_SIGNIFICANCE_LEVEL                         "0.01"
#define STEER_JSON_VALUE_DOUBLE_PRECISION_FLOATING_POINT                    "double precision floating point"
#define STEER_JSON_VALUE_EXTENDED_PRECISION_FLOATING_POINT                  "extended precision floating point"
#define STEER_JSON_VALUE_FAIL                                               "fail"
#define STEER_JSON_VALUE_FALSE                                              "false"
#define STEER_JSON_VALUE_FORWARD                                            "forward"
#define STEER_JSON_VALUE_FULL                                               "full"
#define STEER_JSON_VALUE_INCONCLUSIVE                                       "inconclusive"
#define STEER_JSON_VALUE_MATRICES                                           "matrices"
#define STEER_JSON_VALUE_MAXIMUM_SIGNIFICANCE_LEVEL                         "0.01"
#define STEER_JSON_VALUE_MINIMUM_SIGNIFICANCE_LEVEL                         "0.001"
#define STEER_JSON_VALUE_MODERATE                                           "moderate"
#define STEER_JSON_VALUE_NO                                                 "no"
#define STEER_JSON_VALUE_PASS                                               "pass"
#define STEER_JSON_VALUE_PROBABILITY_VALUES                                 "probability values"
#define STEER_JSON_VALUE_QUICK                                              "quick"
#define STEER_JSON_VALUE_REVERSE                                            "reverse"
#define STEER_JSON_VALUE_RUNS                                               "runs"
#define STEER_JSON_VALUE_SIGNED_8_BIT_INTEGER                               "signed 8-bit integer"
#define STEER_JSON_VALUE_SIGNED_16_BIT_INTEGER                              "signed 16-bit integer"
#define STEER_JSON_VALUE_SIGNED_32_BIT_INTEGER                              "signed 32-bit integer"
#define STEER_JSON_VALUE_SIGNED_64_BIT_INTEGER                              "signed 64-bit integer"
#define STEER_JSON_VALUE_SIMPLE                                             "simple"
#define STEER_JSON_VALUE_SINGLE_PRECISION_FLOATING_POINT                    "single precision floating point"
#define STEER_JSON_VALUE_STANDARD                                           "standard"
#define STEER_JSON_VALUE_SUBSTRINGS                                         "substrings"
#define STEER_JSON_VALUE_SUMMARY                                            "summary"
#define STEER_JSON_VALUE_TESTS                                              "tests"
#define STEER_JSON_VALUE_THREADS                                            "threads"
#define STEER_JSON_VALUE_TRUE                                               "true"
#define STEER_JSON_VALUE_UNSIGNED_8_BIT_INTEGER                             "unsigned 8-bit integer"
#define STEER_JSON_VALUE_UNSIGNED_16_BIT_INTEGER                            "unsigned 16-bit integer"
#define STEER_JSON_VALUE_UNSIGNED_32_BIT_INTEGER                            "unsigned 32-bit integer"
#define STEER_JSON_VALUE_UNSIGNED_64_BIT_INTEGER                            "unsigned 64-bit integer"
#define STEER_JSON_VALUE_UTF_8_STRING                                       "utf-8 string"
#define STEER_JSON_VALUE_VALID                                              "valid"
#define STEER_JSON_VALUE_VISITS                                             "visits"
#define STEER_JSON_VALUE_YES                                                "yes"

// Undefined values
#define STEER_JSON_UNITS_UNDEFINED  NULL
#define STEER_JSON_VALUE_UNDEFINED  NULL

// =================================================================================================
#endif	// __STEER_JSON_CONSTANTS_H__
// =================================================================================================
